# Generated by Django 6.0.7 on 2026-07-10 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du restaurant')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('primary_color', models.CharField(default='#1e40af', max_length=7, verbose_name='Couleur primaire')),
                ('secondary_color', models.CharField(default='#f59e0b', max_length=7, verbose_name='Couleur secondaire')),
                ('background_color', models.CharField(default='#f9fafb', max_length=7, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#1f2937', max_length=7, verbose_name='Couleur du texte')),
                ('header_opacity', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Opacité du header')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2, verbose_name='Langue du menu')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name="Abonnement jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Menu actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_image', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='Image QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
            },
        ),
    ]
